### ISSUE TITLE
How to find token?

### ISSUE THREAD

**Issue by ragnar123** [hhaidar/hubot-lets-chat#5]
I would like to try hubot-lets-chat, but I am not able to find the variable HUBOT_LCB_TOKEN.

I have lets-chat running on a server, but I am not sure how I can generate tokens. Am I missing something?

**Comment by sibartlett** [comment]
You can get an auth token from the drop down user menu in Let's Chat.

If there is no option for Auth tokens, you'll need to update to the latest code - there was a bug that has now been fixed.

**Comment by ragnar123** [comment]
The Auth tokens option was missing in the interface. I pulled the latest code and it appeared in the menu.

Thanks!
